version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  aws-ecs: circleci/aws-ecs@0.0.10

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          create-repo: true
          dockerfile: Dockerfile
          path: .
          region: AWS_REGION
          repo: crud-users
          tag: "$CIRCLE_SHA1"
#      - aws-ecs/deploy-service-update:
#          requires:
#            - aws-ecr/build-and-push-image
#          family: 'proyectofrases-service'
#          cluster-name: 'proyectofrases-service'
#          container-image-name-updates: 'container=proyectofrases-service,tag=${CIRCLE_SHA1}'
#
